language: nix
#nix: 2.0.4

env:
  global:
    # Ubuntu version
    - LINUX_DIST=xenial
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      addons:
       apt:
         packages:
           # Misc
           - python-yaml
         sources:

before_install:

install:
    - sudo pip install codecov
script:
    ############################################################################
    # Build main and tests
    ############################################################################
    - nix-shell
    - mkdir build
    - cd build
    - cmake -GNinja -DBUILD_COVERAGE=ON -DBUILD_DEPENDENCIES=OFF ..
    - cmake --build .
    - exit
after_success:
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f "result/tsm_test-coverage/tsm_test.profdata" || echo "Codecov did not collect coverage reports"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master


after_failure:
  # show actions of the OOM killer
  - echo pwd
  - sudo dmesg
