language: nix cpp
nix: 2.0.4

env:
  global:
    # Ubuntu version
    - LINUX_DIST=xenial
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: g++
      addons:
       apt:
         packages:
           # Misc
           - python-yaml
         sources:

before_install:

install:
    - sudo pip install codecov

    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - nix-shell
     - mkdir -p build
     - cd build
     # This step will reconfigure to detect dependencies locally and build tsm 
     - cmake -DBUILD_DEPENDENCIES=OFF -DBUILD_COVERAGE=ON ..
     # This will run the unit tests as well
     - make -j`nproc --all` coverage
     # generate documentation
     - make -j`nproc --all` tsm_doc

after_success:
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f "lcov.info" || echo "Codecov did not collect coverage reports"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master


after_failure:
  # show actions of the OOM killer
  - echo pwd
  - sudo dmesg
